### PR TITLE
add Gist + remove dismounting the iframe

### PR DESCRIPTION
**Pull request by Ennoriel**
This PR is related to the discussion #369 and aims to:
- add the Gist iframe
- load the screen a little bit before coming to the screen
- remove the component dismounting when leaving the screen

The formatting seems off. I didn't know how to run pretty-quick properly. It kept saying no files changed.
I didn't add the summary since it needs another rehype library to wrap the titles with anchors in order to link to them.

### CODE REVIEW

**Comment by spences10** [comment]
Hey @Ennoriel thanks! I'll take a look at this locally!

Not sure what the issue is with pretty quick, should just run from `pnpm run format` it might be a mixture of my vscode settings.

Did you mention that this would be a breaking change? Looks like this doesn't affect the current API for the general observer, I'll dig into it later

**Comment by spences10** [comment]
Hm! For some reason running this locally the general observer isn't rendering the embeds??

**Comment by Ennoriel** [comment]
Hey @spences10 what exactly do you see? Do you have any error in your console. The dev site is working fine for me on Ffx, Chrome and Edge on Windows :s

**Comment by spences10** [comment]
Probably not as the deployed version is working fine

**Comment by Ennoriel** [comment]
It seems to be related to not having .env nor .env.development locally on this branch and it does not find PUBLIC_FATHOM_ID

**Comment by Ennoriel** [comment]
(by the way, adding analytic cookies without a cookie notice is not a good practice and not legal in EU :s)

**Comment by spences10** [comment]
Ah! Yeah, I'm running your version without adding in a dummy `.env` file.

There's no cookies being added, I use Fathom analytics and LOATHE cookie banners.

Fathom analytics doesn't require cookies, is GDPR compliant and respects the privacy of visitors to my site that use it. Here: https://usefathom.com/docs/troubleshooting/cookies

Great service, been using it for years! If you want to check it out you can use my referral link: https://usefathom.com/ref/HG492L

**Comment by spences10** [comment]
I’m going to take a look at automating releases for this, it’ll get published sometime in the next couple of days

**Comment by Ennoriel** [comment]
Thanks!

I should have looked a bit more carefully about the cookies before posting that :|

No worries for the release.

If you want an example with githib actions npm release automation, you have to options:
- without a changelog or with a changelog generated locally: you can check the [svelte-awesome-color-picker repo](https://github.com/Ennoriel/svelte-awesome-color-picker) for a github workflow example: : every publish on master will run the CI. If the node-modules version has changed, the job will succeed and publish a new version. It will fail otherwise.
- with a changelog generated with changesets/cli: one example is on the [Mdsvex repo](https://github.com/pngwn/mDsveX)

**Comment by spences10** [comment]
Ah! Nice! The MDSveX one looks like something I'd like to implement!

**Pull request merged**
