### PR TITLE
feat(tweet): darkmode support

### PR DESCRIPTION
**Pull request by ryoppippi**
According [this page](https://devcommunity.x.com/t/embedded-tweets-night-mode/109244), we can embed twitter card in night mode using `data-theme='dark'`

### CODE REVIEW

**Review by spences10 — APPROVED** [review]

**Comment by ryoppippi** [comment]
@spences10 
Hi!
Thank you for your review! but I modified the option name.
Please check it out!

**Comment by spences10** [comment]
balls! forgot to add this to the latest release!

**Comment by spences10** [comment]
Hey @ryoppippi 

Couple of things, could you update the docs `apps/web/src/routes/+page.md`?

```html
<Tweet
	tweetLink="adamwathan/status/959078631434731521"
	theme="dark"
/>
```

Also, a nice feature would be to pass some `iframe_styles` like in the https://github.com/spences10/sveltekit-embed/blob/main/packages/sveltekit-embed/src/lib/components/bluesky.svelte component?

Looks a bit janky without them 😅

image

**Comment by spences10** [comment]
err, not quite 😅

did you check out the preview on local before submitting?

image

I removed the css variables and targeted the iframe instead, apologies I noticed that there's not an actual ifram element in this component 😅

**Comment by ryoppippi** [comment]
@spences10 Oh, wait I was still working, but you fixed!
Thank you so much

**Comment by ryoppippi** [comment]
@spences10 Thank you for your refactoring!
The next time you COMMIT, you do not have to confirm until you send the REVIEW request again.
However, this time it was helpful. I'll CONTRIBUTE again！！

**Pull request merged**
